---
- name: Add apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install repository
  become: true
  vars:
    repo_url: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release.stdout }} stable"
  apt_repository:
    repo: "{{ repo_url }}"
    state: present
    update_cache: yes
  when: repo_url not in apt_sources

- name: Create docker group
  become: true
  group:
    name: docker
    system: yes
    state: present

- name: Adding {{ local_user_username }} to the docker group
  become: true
  user:
    name: "{{ local_user_username }}"
    groups: docker
    append: yes

- name: Install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present

